Mox.defmock(Stripe.CustomerMock, for: Stripe.CustomerBehaviour)
Mox.defmock(Ysc.AccountsMock, for: Ysc.Accounts.Behaviour)
Mox.defmock(Ysc.Quickbooks.ClientMock, for: Ysc.Quickbooks.ClientBehaviour)
Mox.defmock(Ysc.StripeMock, for: Ysc.StripeBehaviour)
Mox.defmock(Ysc.KeilaMock, for: Ysc.Keila.Behaviour)
