import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ysc, YscWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

config :ysc, dev_routes: false

database_url = System.get_env("DATABASE_URL", "")

maybe_ipv6 =
  if System.get_env("ECTO_IPV6") in ~w(true 1), do: [:inet6], else: []

config :ysc, Ysc.Repo,
  # ssl: true,
  url: database_url,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
  socket_options: maybe_ipv6

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Ysc.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Mailer configuration is moved to runtime.exs for runtime evaluation

# Do not print debug messages in production
# Allow override via LOG_LEVEL environment variable (e.g., for sandbox deployments)
log_level =
  case System.get_env("LOG_LEVEL") do
    "debug" -> :debug
    "info" -> :info
    "warn" -> :warn
    "error" -> :error
    _ -> :info
  end

config :logger, level: log_level

config :sentry,
  dsn:
    "https://9f1197d8becaf697a4ca018daa8c88b5@o4510359659216896.ingest.us.sentry.io/4510359660396544",
  environment_name: Mix.env(),
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()]

# LiveView Native Stylesheet output in production: keep it small.
config :live_view_native_stylesheet,
  annotations: false,
  pretty: false

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
