import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ysc, YscWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :ysc, dev_routes: false

database_url = System.get_env("DATABASE_URL", "")
maybe_ipv6 = if System.get_env("ECTO_IPV6") in ~w(true 1), do: [:inet6], else: []

config :ysc, Ysc.Repo,
  # ssl: true,
  url: database_url,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
  socket_options: maybe_ipv6

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Ysc.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

config :ysc, Ysc.Mailer,
  adapter: Swoosh.Adapters.AmazonSES,
  region: "us-west-1",
  access_key_id: System.get_env("SES_AWS_ACCESS_KEY_ID"),
  secret_access_key: System.get_env("SES_AWS_SECRET_ACCESS_KEY")

# Do not print debug messages in production
config :logger, level: :info

config :sentry,
  dsn:
    "https://9f1197d8becaf697a4ca018daa8c88b5@o4510359659216896.ingest.us.sentry.io/4510359660396544",
  environment_name: Mix.env(),
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
